repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: imports
        additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.3
    hooks:
      - id: isort
        exclude: imports
