# This workflow runs the python unit tests
name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  build-310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run unit tests
        run: docker build . --target=test --build-arg PYTHON_VERSION=3.10
  build-311:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run unit tests
        run: docker build . --target=test --build-arg PYTHON_VERSION=3.11
  build-312:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run unit tests
        run: docker build . --target=test --build-arg PYTHON_VERSION=3.12
